export const ON_FETCH_POSTS_START = "ON_FETCH_POSTS_START";
export const ON_FETCH_POSTS_SUCCESS = "ON_FETCH_POSTS_SUCCESS";
export const ON_POSTS_FAILED = "ON_POSTS_FAILED";
export const ON_POST_SAVE_START = "ON_POST_SAVE_START";
export const ON_POST_SAVE_SUCCESS = "ON_POST_SAVE_SUCCESS";
export const ON_GET_POST_START = "ON_GET_POST_START";
export const ON_GET_POST_SUCCESS = "ON_GET_POST_SUCCESS";
